name: UnitTests

on:
  push:

jobs:
  setup-deno:
    name: Setup Deno
    runs-on: ubuntu-latest
    steps:
      - name: Set up Deno
        uses: denoland/setup-deno@v1.1.3
      - name: Display event information
        run: |
            cd tests
            deno test EnvTests.ts
            deno test LexerTests.ts
